apiVersion: v1
kind: Service
metadata:
  name: faas-netesd
  namespace: openfaas
  labels:
    app: faas-netesd
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: faas-netesd
---
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: faas-netesd
  namespace: openfaas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: faas-netesd
    spec:
      serviceAccountName: faas-controller
      containers:
      - name: faas-netesd
        image: functions/faas-netesd:0.4.3-arm64
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 50Mi
          limits:
            memory: 50Mi
        env:
        - name: function_namespace
          value: openfaas-fn
        - name: read_timeout
          value: "10"
        - name: write_timeout
          value: "10"
