{{- $functionNs := default .Release.Namespace .Values.functionNamespace }}
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: faas-netesd
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: faas-netesd
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: faas-netesd
    spec:
      serviceAccountName: faas-controller
      containers:
      - name: faas-netesd
        image: {{ .Values.images.controller }}
        imagePullPolicy: Always
        env:
        - name: function_namespace
          value: {{ $functionNs | quote }}
        - name: read_timeout
          value: "{{ .Values.faasnetesd.readTimeout }}"
        - name: write_timeout
          value: "{{ .Values.faasnetesd.writeTimeout }}"
        - name: image_pull_policy
          value: {{ .Values.faasnetesd.imagePullPolicy | quote }}
        ports:
        - containerPort: 8080
          protocol: TCP
