{{- $functionNs := default .Release.Namespace .Values.functionNamespace }}
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: gateway
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: gateway
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: {{ .Values.images.gateway }}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 10
          timeoutSeconds: 2

        env:
        - name: read_timeout
          value: "{{ .Values.gateway.readTimeout }}"
        - name: write_timeout
          value: "{{ .Values.gateway.writeTimeout }}"
        - name: upstream_timeout
          value: "{{ .Values.gateway.upstreamTimeout }}"
        - name: functions_provider_url
          value: "http://faas-netesd.{{ .Release.Namespace }}.svc.cluster.local.:8080/"
        - name: functions_dns_suffix
          value: "svc.cluster.local."
        {{- if .Values.async }}
        - name: faas_nats_address
          value: "nats.{{ .Release.Namespace }}.svc.cluster.local."
        - name: faas_nats_port
          value: "4222"
        - name: direct_functions
          value: "true"
        - name: direct_functions_suffix
          value: "{{ $functionNs }}.svc.cluster.local."
        {{- end }}
        ports:
        - containerPort: 8080
          protocol: TCP