{{- if and .Values.exposeServices .Values.async }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: nats
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: nats-external
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - port: 4222
      protocol: TCP
      targetPort: 4222
  selector:
    app: nats
{{- end }}
