apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: faas-netesd
  namespace: openfaas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: faas-netesd
    spec:
      serviceAccountName: faas-controller
      containers:
      - name: faas-netesd
        image: functions/faas-netesd:0.5.5
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 150Mi   
          limits:
            memory: 150Mi   # Adjust to suit needs
        env:
        - name: function_namespace
          value: openfaas-fn
        - name: read_timeout
          value: "20s"
        - name: write_timeout
          value: "20s"
        - name: image_pull_policy
          value: "Always"
