apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: queue-worker
  namespace: openfaas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: queue-worker
    spec:
      containers:
      - name:  queue-worker
        image: functions/queue-worker:0.4.3
        imagePullPolicy: Always
        env:
        - name: max_inflight      # Max number of items in-flight
          value: "1"
        - name: ack_wait          # Max duration of any async task / request
          value: "30s"
        - name: faas_function_suffix
          value: ".openfaas-fn.svc.cluster.local."  # absolute DNS will suppress search domains
